import type { ServiceDefinition } from "@locainfra/server";

const health = (test: string[]) => ({ test, interval: "5s", retries: 10 });

/**
 * Catalog served by the mock API: the three real definitions under
 * `catalog/` (with their M3 `data`, `seed`, `secretOptions` and `import`
 * blocks) plus mock-only MySQL, MongoDB, MinIO and RabbitMQ entries so
 * every category and brand icon can be exercised.
 */
export const MOCK_CATALOG: ServiceDefinition[] = [
	{
		id: "postgres",
		name: "PostgreSQL",
		description: "Relational database with extensions like pgvector.",
		category: "database",
		tags: ["sql", "relational"],
		icon: "postgres",
		image: "postgres:{{version}}-alpine",
		versions: ["17", "16", "15"],
		defaultVersion: "17",
		port: { container: 5432, default: 5432, range: [5432, 5499] },
		secrets: ["POSTGRES_PASSWORD"],
		config: {
			POSTGRES_USER: {
				default: "postgres",
				pattern: "^[A-Za-z0-9_][A-Za-z0-9_.-]*$",
			},
			POSTGRES_DB: {
				default: "{{stack.name}}",
				pattern: "^[A-Za-z0-9_][A-Za-z0-9_-]*$",
			},
		},
		env: {},
		volumes: [{ name: "data", path: "/var/lib/postgresql/data" }],
		healthcheck: health(["CMD", "pg_isready"]),
		exports: {
			DATABASE_URL:
				"postgres://{{config.POSTGRES_USER}}:{{secrets.POSTGRES_PASSWORD}}@127.0.0.1:{{port}}/{{config.POSTGRES_DB}}",
			PGHOST: "127.0.0.1",
			PGPORT: "{{port}}",
		},
		primaryExport: "DATABASE_URL",
		snippets: {
			node: 'import pg from "pg";\nconst pool = new pg.Pool({ connectionString: process.env.KEY });',
			python: 'import os, psycopg\nconn = psycopg.connect(os.environ["KEY"])',
			go: 'conn, err := pgx.Connect(ctx, os.Getenv("KEY"))',
		},
		studio: { panel: "sql" },
		secretOptions: { POSTGRES_PASSWORD: { bakedIntoVolume: true } },
		data: {
			kind: "sql",
			label: "Tables",
			listObjects: [
				"psql",
				"-X",
				"-U",
				"{{config.POSTGRES_USER}}",
				"-d",
				"{{config.POSTGRES_DB}}",
				"-A",
				"-t",
				"-c",
				"SELECT tablename FROM pg_tables WHERE schemaname = 'public' ORDER BY tablename",
			],
			runQuery: [
				"psql",
				"-X",
				"-U",
				"{{config.POSTGRES_USER}}",
				"-d",
				"{{config.POSTGRES_DB}}",
				"--csv",
				"-v",
				"ON_ERROR_STOP=1",
				"-c",
				"{{query}}",
			],
			defaultQuery: 'SELECT *\nFROM "{{object}}"\nLIMIT 100;',
		},
		seed: {
			mountPath: "/docker-entrypoint-initdb.d",
			fileName: "seed.sql",
			run: [
				"psql",
				"-X",
				"-q",
				"-U",
				"{{config.POSTGRES_USER}}",
				"-d",
				"{{config.POSTGRES_DB}}",
				"-v",
				"ON_ERROR_STOP=1",
				"-f",
				"-",
			],
		},
		import: { images: ["postgres", "postgis/postgis", "pgvector/pgvector"] },
	},
	{
		id: "mysql",
		name: "MySQL",
		description:
			"The classic relational database, wire-compatible with PlanetScale.",
		category: "database",
		tags: ["sql"],
		icon: "mysql",
		image: "mysql:{{version}}",
		versions: ["8.4", "8.0"],
		defaultVersion: "8.4",
		port: { container: 3306, default: 3306, range: [3306, 3399] },
		secrets: ["MYSQL_PASSWORD"],
		config: {
			MYSQL_USER: { default: "app", pattern: "^[A-Za-z0-9_]+$" },
			MYSQL_DATABASE: {
				default: "{{stack.name}}",
				pattern: "^[A-Za-z0-9_-]+$",
			},
		},
		env: {},
		volumes: [{ name: "data", path: "/var/lib/mysql" }],
		healthcheck: health(["CMD", "mysqladmin", "ping"]),
		exports: {
			MYSQL_URL:
				"mysql://{{config.MYSQL_USER}}:{{secrets.MYSQL_PASSWORD}}@127.0.0.1:{{port}}/{{config.MYSQL_DATABASE}}",
		},
		primaryExport: "MYSQL_URL",
		import: { images: ["mysql", "mariadb"] },
		snippets: {
			node: 'import mysql from "mysql2/promise";\nconst db = await mysql.createConnection(process.env.KEY);',
		},
	},
	{
		id: "mongodb",
		name: "MongoDB",
		description: "Document database for JSON-shaped data.",
		category: "database",
		tags: ["nosql", "document"],
		icon: "mongodb",
		image: "mongo:{{version}}",
		versions: ["8", "7"],
		defaultVersion: "8",
		port: { container: 27017, default: 27017, range: [27017, 27099] },
		secrets: ["MONGO_PASSWORD"],
		config: {},
		env: {},
		volumes: [{ name: "data", path: "/data/db" }],
		healthcheck: health(["CMD", "mongosh", "--eval", "db.runCommand('ping')"]),
		exports: {
			MONGODB_URI:
				"mongodb://root:{{secrets.MONGO_PASSWORD}}@127.0.0.1:{{port}}",
		},
		primaryExport: "MONGODB_URI",
		import: { images: ["mongo"] },
	},
	{
		id: "minio",
		name: "MinIO (S3)",
		description: "S3-compatible object storage for uploads and assets.",
		category: "storage",
		categoryLabel: "Storage",
		tags: ["s3", "object-storage"],
		icon: "minio",
		image: "minio/minio:{{version}}",
		versions: ["latest"],
		defaultVersion: "latest",
		port: { container: 9000, default: 9000, range: [9000, 9099] },
		secrets: ["MINIO_ROOT_PASSWORD"],
		config: { MINIO_ROOT_USER: { default: "locainfra" } },
		env: {},
		volumes: [{ name: "data", path: "/data" }],
		healthcheck: health(["CMD", "mc", "ready", "local"]),
		exports: {
			S3_ENDPOINT: "http://127.0.0.1:{{port}}",
			S3_ACCESS_KEY_ID: "{{config.MINIO_ROOT_USER}}",
			S3_SECRET_ACCESS_KEY: "{{secrets.MINIO_ROOT_PASSWORD}}",
		},
		primaryExport: "S3_ENDPOINT",
		import: { images: ["minio/minio"] },
	},
	{
		id: "redis",
		name: "Redis",
		description: "Classic redis:// for ioredis, redis-py, go-redis.",
		category: "cache",
		categoryLabel: "Redis",
		tags: ["key-value", "cache", "queue"],
		icon: "redis",
		image: "redis:{{version}}-alpine",
		versions: ["8", "7"],
		defaultVersion: "7",
		port: { container: 6379, default: 6379, range: [6379, 6449] },
		secrets: ["REDIS_PASSWORD"],
		config: {},
		env: {},
		volumes: [{ name: "data", path: "/data" }],
		healthcheck: health(["CMD", "redis-cli", "ping"]),
		exports: {
			REDIS_URL: "redis://:{{secrets.REDIS_PASSWORD}}@127.0.0.1:{{port}}",
			REDIS_HOST: "127.0.0.1",
			REDIS_PORT: "{{port}}",
		},
		primaryExport: "REDIS_URL",
		snippets: {
			node: 'import Redis from "ioredis";\nconst redis = new Redis(process.env.KEY);',
			python: 'import os, redis\nr = redis.from_url(os.environ["KEY"])',
			go: 'opt, _ := redis.ParseURL(os.Getenv("KEY"))\nrdb := redis.NewClient(opt)',
		},
		studio: { panel: "redis" },
		data: {
			kind: "redis",
			label: "Key patterns",
			objects: ["*"],
			runQuery: ["redis-cli", "--csv", "{{query}}"],
			defaultQuery: "SCAN 0 MATCH {{object}} COUNT 100",
		},
		import: { images: ["redis", "valkey/valkey"] },
	},
	{
		id: "upstash-redis",
		name: "Upstash Redis (REST)",
		description: "REST-compatible Redis that matches serverless prod.",
		category: "cache",
		categoryLabel: "Redis",
		tags: ["redis", "rest", "upstash", "serverless"],
		icon: "upstash",
		image: "hiett/serverless-redis-http:{{version}}",
		versions: ["latest"],
		defaultVersion: "latest",
		port: { container: 80, default: 8079, range: [8079, 8149] },
		dependsOn: ["redis"],
		secrets: ["SRH_TOKEN"],
		config: {},
		env: {},
		volumes: [],
		healthcheck: health(["CMD", "nc", "-z", "127.0.0.1", "80"]),
		exports: {
			UPSTASH_REDIS_REST_URL: "http://127.0.0.1:{{port}}",
			UPSTASH_REDIS_REST_TOKEN: "{{secrets.SRH_TOKEN}}",
		},
		primaryExport: "UPSTASH_REDIS_REST_URL",
		snippets: {
			node: 'import { Redis } from "@upstash/redis";\nconst redis = Redis.fromEnv(); // reads KEY + token',
			python: "from upstash_redis import Redis\nredis = Redis.from_env()",
			go: '// POST to os.Getenv("KEY") with Authorization: Bearer <token>',
		},
		data: { kind: "none" },
		import: { images: ["hiett/serverless-redis-http", "upstash/redis-http"] },
	},
	{
		id: "rabbitmq",
		name: "RabbitMQ",
		description: "AMQP message broker with a management UI.",
		category: "queue",
		tags: ["amqp", "queue"],
		icon: "rabbitmq",
		image: "rabbitmq:{{version}}-management-alpine",
		versions: ["4", "3.13"],
		defaultVersion: "4",
		port: { container: 5672, default: 5672, range: [5672, 5699] },
		secrets: ["RABBITMQ_DEFAULT_PASS"],
		config: { RABBITMQ_DEFAULT_USER: { default: "app" } },
		env: {},
		volumes: [{ name: "data", path: "/var/lib/rabbitmq" }],
		healthcheck: health(["CMD", "rabbitmq-diagnostics", "ping"]),
		exports: {
			AMQP_URL:
				"amqp://{{config.RABBITMQ_DEFAULT_USER}}:{{secrets.RABBITMQ_DEFAULT_PASS}}@127.0.0.1:{{port}}",
		},
		primaryExport: "AMQP_URL",
		import: { images: ["rabbitmq"] },
	},
];
