import type {
	AddServiceBody,
	PersistMode,
	ServiceDefinition,
	ServiceStatus,
	StackServiceEntry,
} from "@locainfra/server";
import { normalizeSeedPath } from "./seed-path";

/** Pattern of service instance names. */
export const INSTANCE_NAME_PATTERN = /^[a-z][a-z0-9-]*$/;
/** Lowest host port the form accepts (no privileged ports). */
export const MIN_HOST_PORT = 1024;
/** Highest TCP port. */
export const MAX_HOST_PORT = 65535;

/** Values of the service Config form. */
export interface ConfigFormValues {
	name: string;
	version: string;
	/** Host port as typed (validated to an integer). */
	port: string;
	persist: PersistMode;
	/** Config entry values keyed by the definition's config keys. */
	config: Record<string, string>;
	/**
	 * Secrets chosen with Regenerate, by catalog secret name. Omitted ones
	 * are generated by the server.
	 */
	secrets: Record<string, string>;
	/** Seed file as typed (only for definitions with a `seed` block; `""` = none). */
	seed: string;
}

/** What the form knows about the target project. */
export interface ConfigContext {
	readonly project: string;
	readonly definition: ServiceDefinition;
	/** Services already in the project (names and host ports). */
	readonly services: readonly Pick<ServiceStatus, "name" | "hostPort">[];
	/**
	 * Port proposed by the server (`GET /api/catalog/:type/free-port`), which
	 * also sees other projects' pins and bound ports. `null`/omitted falls back
	 * to the definition's default or the next port free in this project.
	 */
	readonly suggestedPort?: number | null;
}

/** Host port value that lets the server allocate one (`port: auto`). */
export const AUTO_PORT = "auto";

const NAME_BASE: Readonly<Record<string, string>> = {
	database: "db",
	cache: "cache",
	queue: "queue",
	storage: "storage",
	mail: "mail",
	search: "search",
};

/**
 * First free instance name for a definition (`db`, `db-2`, …).
 *
 * @param definition - Catalog definition.
 * @param taken - Existing instance names.
 * @returns A unique name.
 */
export function defaultInstanceName(
	definition: ServiceDefinition,
	taken: readonly string[],
): string {
	const base = NAME_BASE[definition.category] ?? definition.id;
	let name = base;
	for (let i = 2; taken.includes(name); i += 1) name = `${base}-${i}`;
	return name;
}

/**
 * The service already bound to a host port in this project.
 * (Other projects' ports are not visible to the client; the server's 409
 * `PORT_CONFLICT` covers those.)
 *
 * @param ctx - Project context.
 * @param port - Host port.
 * @returns The owning instance name.
 */
export function portOwner(
	ctx: ConfigContext,
	port: number,
): string | undefined {
	return ctx.services.find((s) => s.hostPort === port)?.name;
}

/**
 * Next port at or after `from` not used by this project (the API has no
 * free-port route, so this is computed from the project status).
 *
 * @param ctx - Project context.
 * @param from - First candidate.
 * @returns A free port, or `undefined` when none is left below 65536.
 */
export function nextFreePort(
	ctx: ConfigContext,
	from: number,
): number | undefined {
	const taken = new Set(ctx.services.map((s) => s.hostPort));
	for (
		let port = Math.max(from, MIN_HOST_PORT);
		port <= MAX_HOST_PORT;
		port += 1
	) {
		if (!taken.has(port)) return port;
	}
	return undefined;
}

/**
 * Resolves the simple templates a config default may use.
 *
 * @param template - Default value, e.g. `{{stack.name}}`.
 * @param project - Project name.
 * @param name - Instance name.
 * @returns The value shown in the form.
 */
export function resolveDefault(
	template: string,
	project: string,
	name: string,
): string {
	return template
		.replaceAll("{{stack.name}}", project)
		.replaceAll("{{name}}", name);
}

/**
 * Initial form values for a definition in a project.
 *
 * @param ctx - Project context.
 * @returns Defaults: unique name, default version, free port, volume, config defaults.
 */
export function buildDefaults(ctx: ConfigContext): ConfigFormValues {
	const { definition } = ctx;
	const name = defaultInstanceName(
		definition,
		ctx.services.map((s) => s.name),
	);
	const suggested =
		ctx.suggestedPort != null && !portOwner(ctx, ctx.suggestedPort)
			? ctx.suggestedPort
			: undefined;
	const port =
		suggested ??
		(portOwner(ctx, definition.port.default)
			? (nextFreePort(ctx, definition.port.range[0]) ?? definition.port.default)
			: definition.port.default);
	return {
		name,
		version: definition.defaultVersion,
		port: String(port),
		persist: definition.volumes.length ? "volume" : "ephemeral",
		config: Object.fromEntries(
			Object.entries(definition.config).map(([key, value]) => [
				key,
				resolveDefault(value.default, ctx.project, name),
			]),
		),
		secrets: {},
		seed: "",
	};
}

/**
 * Validates the instance name.
 *
 * @param name - Proposed name.
 * @param ctx - Project context.
 * @returns Error message or `undefined`.
 */
export function validateInstanceName(
	name: string,
	ctx: ConfigContext,
): string | undefined {
	if (!name) return "Name is required.";
	if (!INSTANCE_NAME_PATTERN.test(name))
		return "Use lowercase letters, numbers and dashes.";
	if (ctx.services.some((s) => s.name === name))
		return `A service named “${name}” already exists in ${ctx.project}.`;
	return undefined;
}

/**
 * Validates the host port (range, then conflicts within the project).
 * `auto` is accepted: the server allocates a free port on create.
 *
 * @param port - Port as typed.
 * @param ctx - Project context.
 * @returns Error message or `undefined`.
 */
export function validateHostPort(
	port: string,
	ctx: ConfigContext,
): string | undefined {
	if (port === AUTO_PORT) return undefined;
	if (
		!/^\d+$/.test(port) ||
		Number(port) < MIN_HOST_PORT ||
		Number(port) > MAX_HOST_PORT
	)
		return `Port must be between ${MIN_HOST_PORT} and ${MAX_HOST_PORT}, or auto.`;
	const owner = portOwner(ctx, Number(port));
	return owner ? `Port ${port} is in use by ${owner}.` : undefined;
}

/**
 * Per-key errors of config values against the definition's patterns.
 *
 * @param definition - Catalog definition.
 * @param config - Values from the form.
 * @returns Key → message for invalid values.
 */
export function configErrors(
	definition: ServiceDefinition,
	config: Readonly<Record<string, string>>,
): Record<string, string> {
	const out: Record<string, string> = {};
	for (const [key, spec] of Object.entries(definition.config)) {
		const value = config[key] ?? "";
		if (!value) {
			out[key] = "Required.";
			continue;
		}
		if (spec.pattern) {
			let valid = true;
			try {
				valid = new RegExp(spec.pattern).test(value);
			} catch {
				valid = true;
			}
			if (!valid)
				out[key] = "Letters, digits, dots, dashes and underscores only.";
		}
	}
	return out;
}

/**
 * The port to offer in "Use N": the next free one after the typed port (or
 * from the catalog range when the typed value is not a number).
 *
 * @param values - Form values.
 * @param ctx - Project context.
 * @returns A free port.
 */
export function portSuggestion(
	values: ConfigFormValues,
	ctx: ConfigContext,
): number | undefined {
	const typed = /^\d+$/.test(values.port) ? Number(values.port) : Number.NaN;
	const inRange = typed >= MIN_HOST_PORT && typed <= MAX_HOST_PORT;
	return nextFreePort(ctx, inRange ? typed : ctx.definition.port.range[0]);
}

/**
 * The `locainfra.yaml` entry the form describes. Config keys equal to their
 * (resolved) defaults are omitted so the file stays minimal.
 *
 * @param values - Form values.
 * @param ctx - Project context.
 * @returns The stack entry.
 */
export function toStackEntry(
	values: ConfigFormValues,
	ctx: ConfigContext,
): StackServiceEntry {
	const config: Record<string, string> = {};
	for (const [key, spec] of Object.entries(ctx.definition.config)) {
		const value = values.config[key];
		if (
			value !== undefined &&
			value !== resolveDefault(spec.default, ctx.project, values.name)
		) {
			config[key] = value;
		}
	}
	const port = Number(values.port);
	const seed = ctx.definition.seed ? normalizeSeedPath(values.seed) : "";
	return {
		type: ctx.definition.id,
		version: values.version,
		port: Number.isInteger(port) && port > 0 ? port : "auto",
		persist: values.persist,
		...(Object.keys(config).length ? { config } : {}),
		...(seed ? { seed } : {}),
	};
}

/**
 * Request body of `POST …/services`: the stack entry plus the secrets picked
 * with Regenerate (only the definition's own secret names).
 *
 * @param values - Form values.
 * @param ctx - Project context.
 * @returns The Add service body.
 */
export function toAddBody(
	values: ConfigFormValues,
	ctx: ConfigContext,
): AddServiceBody {
	const secrets = Object.fromEntries(
		Object.entries(values.secrets).filter(
			([key, value]) => ctx.definition.secrets.includes(key) && value,
		),
	);
	return {
		name: values.name,
		...toStackEntry(values, ctx),
		...(Object.keys(secrets).length ? { secrets } : {}),
	};
}

const WORDS: Readonly<Record<string, string>> = {
	DB: "Database",
	DATABASE: "Database",
	USER: "User",
	USERNAME: "User",
	PASSWORD: "Password",
	PASS: "Password",
};

/**
 * Human label of a config key: drops the image prefix (`POSTGRES_DB` → `Database`).
 *
 * @param key - Config key.
 * @returns A short label.
 */
export function configLabel(key: string): string {
	const parts = key.split("_");
	const last = parts.at(-1) ?? key;
	const mapped = WORDS[last];
	if (mapped) return mapped;
	const tail = parts.length > 1 ? parts.slice(1) : parts;
	const text = tail.join(" ").toLowerCase();
	return text.charAt(0).toUpperCase() + text.slice(1);
}

/**
 * Label of a generated secret (`POSTGRES_PASSWORD` → `Password`, `SRH_TOKEN` → `Token`).
 *
 * @param name - Secret name.
 * @returns A short label.
 */
export function secretLabel(name: string): string {
	if (/PASS(WORD)?$/.test(name)) return "Password";
	if (/TOKEN$/.test(name)) return "Token";
	if (/(SECRET|KEY)$/.test(name)) return "Secret key";
	return name;
}
